### PR TITLE
dev-to-prod

### PR DESCRIPTION
**Pull request by Izobov**
Please `click on` the `(^) Preview` tab and select the appropriate sub-template:

- [Pull-Request Template into branch:dev](?expand=1&template=pr_to_dev.md)
- [Pull-Request Template into branch:main](?expand=1&template=pr_to_main.md)

### CODE REVIEW

**Comment by migbash** [comment]
@Izobov What's the reason for the switch to the use of `$: isAuth = !!user;` ?

**Comment by Izobov** [comment]
> @Izobov What's the reason for the switch to the use of `$: isAuth = !!user;` ?

Because on the very first loading it was globalState = "Authenticated" but $userBetarenaSettings.user = null

After page refresh it become normal.

So at this stage $userBetarenaSettings.user is more truly than globalState

**Comment by migbash** [comment]
> > @Izobov What's the reason for the switch to the use of `$: isAuth = !!user;` ?
> 
> 
> 
> Because on the very first loading it was globalState = "Authenticated" but $userBetarenaSettings.user = null
> 
> 
> 
> After page refresh it become normal.
> 
> 
> 
> So at this stage $userBetarenaSettings.user is more truly than globalState
> 
> 
> 
> 
> 
> 
> 
> And it was very difficult to debug to understand why globalState indicates "Authenticated"

We need to fix this the and have it use the `globalState` to keep state consistent, and not create another separate check/validation that is independent for each component as you've done for files in this `PR`.

**Comment by Izobov** [comment]
> > > @Izobov What's the reason for the switch to the use of `$: isAuth = !!user;` ?
> > 
> > 
> > Because on the very first loading it was globalState = "Authenticated" but $userBetarenaSettings.user = null
> > After page refresh it become normal.
> > So at this stage $userBetarenaSettings.user is more truly than globalState
> > And it was very difficult to debug to understand why globalState indicates "Authenticated"
> 
> We need to fix this the and have it use the `globalState` to keep state consistent, and not create another separate check/validation that is independent for each component as you've done for files in this `PR` with the `$: isAuth = !!user`.

Yes, I know. But it's a hot fix that stops our users

And as I said it difficult to debbug reasons. So it will take more time. But for now we need to unlock platform for our users, because they cannot login

**Review by migbash — APPROVED** [review]

**Pull request merged**
